apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: manager2
  namespace: llm-report
spec:
  output:
    to:
      kind: ImageStreamTag
      name: manager2:v0.1
  source:
    type: Git
    git:
      uri: 'https://github.com/digital-iq/llm-report.git'
    contextDir: llm/manager2
    sourceSecret:
      name: github-token-secret
  strategy:
    type: Docker
  triggers:
    - type: ConfigChange
    - type: ImageChange
