apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: orchestrator-route
  namespace: llm-report
  annotations:
    haproxy.router.openshift.io/timeout: 10m
    haproxy.router.openshift.io/timeout-tunnel: 10m
spec:
  to:
    kind: Service
    name: orchestrator-service
  port:
    targetPort: 8080
  tls:
    termination: edge
