apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: llm-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: image-registry.openshift-image-registry.svc:5000/llm-report/orchestrator-image:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MANAGER1_URL
              value: "http://manager1-service.llm-report.svc.cluster.local:8080"
            - name: MANAGER2_URL
              value: "http://manager2-service.llm-report.svc.cluster.local:8080"
            - name: REPORTS_PATH
              value: "/reports"
            - name: ASCIIDOCTOR_CMD
              value: "asciidoctor-pdf"
            - name: FLASK_SECRET_KEY
              value: "changeme"
          volumeMounts:
            - name: reports-volume
              mountPath: /reports
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: reports-volume
          persistentVolumeClaim:
            claimName: orchestrator-reports-pvc

