apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: orchestrator-route
  namespace: llm-report
spec:
  to:
    kind: Service
    name: orchestrator-service
  port:
    targetPort: 8080
  tls:
    termination: edge
